language: r
cache: packages
os: linux

r_packages:
- covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

jobs:
  include:
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel
      env: _R_CHECK_LENGTH_1_LOGIC2_=verbose

r_check_args: "--as-cran"

notifications:
  email:
    on_success: change
    on_failure: change
